### ISSUE TITLE
Stuck with "Waiting for transaction receipt..........."

### ISSUE THREAD

**Issue by aboutlo** [makerdao/dai-cli#2]
I'm trying to use dai CLI on macos 

`$ dai --version` => `dai 0.6.1`
```
export ETH_RPC_URL=https://kovan.infura.io
export ETH_GAS=400000
export ETH_FROM=0x00000000001 (fake address)
```
`$ dai open`
```
Opening cup...
Waiting for hardware wallet confirmation...
Waiting for transaction receipt.............
```

Then I'm stuck ... I tried to run  manually each command from here: 
https://github.com/makerdao/dai-cli/blob/3ac6e5a59a3cb4216619cd23ed32d6d5b2ccbf63/libexec/dai/dai-open

I'm capable to execute the two above comands manually by taking the $tx from etherscan

```
number=$(SETH_TICK=true seth receipt "$tx" blockNumber)
number=$(seth --to-hex "$number")
```

then I'm not able to get an output from seth rpc eth_getLogs 

Do you support MacOS? Can you suggest a way to run the CLI via Max?

Thank you!

**Comment by gbalabasquer** [comment]
infura doesn't return logs

**Comment by aboutlo** [comment]
I see, so you are saying I should run a node in local. Nothing wrong with that but it would be quite handy if I can skip this for now. 

Given that, the doc https://developer.makerdao.com/dai/1/cli is suggesting to use Infura but then if 
`dai open` doesn't work it isn't ideal.

**Comment by gbalabasquer** [comment]
I do not remember since when infura stopped providing logs. But yeah it is not ideal what the doc says.
Take into account the `open` action will work, what doesn't work is getting the cdp id, after creating it. cc @desaperados

**Comment by desaperados** [comment]
We use etherscan to query logs so this is expected to work even with ETH_RPC_URL pointed to infura.

I've just tested the `open` command on Kovan and it's working as expected, returning the correct cup id via the logs, filtered by block number, log signature and `ETH_FROM` address.

Could the issue here be that `ETH_FROM` is a fake address in the above example? The open command requires a successful transaction in order to parse out the new cup id from the logs.

**Comment by aboutlo** [comment]
Thank you very much for your time @desaperados + @gbalabasquer! 
I figured out my issue.

Because I set:
```
export ETH_RPC_URL=https://kovan.infura.io
```

I was run: 
```
 dai open 
```

Instead of

```
 dai --chain kovan open 
```

I assumed that kovan was alredy set because the ETH_RPC_URL was `https://kovan.infura.io`. 
Once i passed `--chain kovan` everything works perfectly so now I have a CDP on kovan 🙌

**Comment by desaperados** [comment]
Ah yes - the dai cli sets contract addresses based on the `--chain` flag so you will need to specify that when using kovan (default is mainnet). You actually don't need to set `ETH_RPC_URL` when using the chain flag as `seth` will [do that for you](https://github.com/dapphub/dapptools/blob/master/src/seth/libexec/seth/seth#L151). There's even a `-C` shortcut so you can just run:

```
dai -C kovan open
```
